### ISSUE TITLE
内存中的 workerNumber 以及 transporterNumber 并不符合实际情况，导致creep数量问题

### ISSUE THREAD

**Issue by 923132714** [HoPGoldy/my-screeps-ai#19]
问题位置: `src\modules\room\spawn\CreepRelease.ts`
![image](https://user-images.githubusercontent.com/25949545/115954808-89405600-a525-11eb-8c68-4b9c6424162b.png)

ho怎么看

https://github.com/LokiSharp/ScreepsScript/issues/6

**Comment by HoPGoldy** [comment]
目前没发现这里出现问题，能复现出来嘛？

**Comment by 923132714** [comment]
现在出现问题的这个已经respawn了，后续如果重现再补充信息

**Comment by 923132714** [comment]
又重现了。。。
![Uploading image.png…]()

**Comment by 923132714** [comment]
https://github.com/923132714/ScreepsScript/issues/15 已解决

你看看我改的对不

**Comment by HoPGoldy** [comment]
> [923132714/ScreepsScript#15](https://github.com/923132714/ScreepsScript/issues/15) 已解决
> 
> 你看看我改的对不

是有这个问题的，已修复，感谢指出🙌
