### ISSUE TITLE
修改creep内存结构

### ISSUE THREAD

**Issue by 923132714** [HoPGoldy/my-screeps-ai#27]
## 将删除creep从立刻延迟到再生时
当前删除creep就会立刻自杀，特别是调整manager和worker，感觉比较浪费，是否可以在creep内存统一增加是否持续生成。像战斗单位那样。

- creep内存增加 keepSpawn? 
  - 有这个参数后，调整数量只需置为不持续生成。
  - 如果没有这个参数就按照默认的情况处理
- 删除creep方法可以增加配置项，选择是否立刻删除，默认为false

在creep频繁调整的时候可以节约能源

**Comment by HoPGoldy** [comment]
`removeCreep` 删除 creep 不会立刻杀掉 creep，详见 [其配置项](https://github.com/HoPGoldy/my-screeps-ai/blob/dev/src/modules/creep/utils.ts#L14)。这个应该就是你说的 “要增加的配置项”。

manager 和 worker 默认都是持续孵化的，`creepRelease.changeBaseUnit` 调整这两者的数量也只是会在其老死后不再继续孵化。

**Comment by 923132714** [comment]
nb
